# Here is the message configuration file for Mizuki.
# This is a really basic example of how you can configure messages.
# For a more in depth dive, go to https://mizuki.astrid.sh/configuration/messages

[join]
content = "%name% joined the server"
[leave]
content = "%name% left"
[chat]
content = "**%name%**: %message%"
[ingame]
content = "&7[&bDiscord&7] %role-colour%%name%&f:&7 %message%"